name: build spack buildcache
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  buildcache-linux-x86:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04 ]
        target: [ x86_64_v2, x86_64_v3 ]
    runs-on: ${{matrix.os}}
    permissions:
      packages: write
    steps: &buildcache-steps
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure target architecture
        run: sed 's/%%SPACK_TARGET%%/${{matrix.target}}/g' spack.yaml.in > spack.yaml

      - name: Set up Spack
        uses: spack/setup-spack@v2.1.1
        with:
          ref: releases/v1.0      # Spack version (examples: develop, releases/v0.23)
          buildcache: false  # Configure oci://ghcr.io/spack/github-actions-buildcache
          color: true       # Force color output (SPACK_COLOR=always)
          path: spack       # Where to clone Spack

      - name: Spec
        run: spack -e . spec -I

      - name: Install
        run: spack -e . install

      - name: Run
        shell: spack-bash {0}
        run: |
          spack env activate .
#          python3 -c 'print("hello world")'

      - name: Push packages and update index
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: spack -e . buildcache push --base-image ubuntu:22.04 --update-index numpex-buildcache
        if: ${{ !cancelled() }}

  buildcache-linux-arm:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04-arm ]
        target: [ zen3, zen4 ]
    runs-on: ${{matrix.os}}
    permissions:
      packages: write
    steps: *buildcache-steps

  buildcache-macos-intel:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-13 ]
        target: [ x86_64_v2, x86_64_v3 ]
    runs-on: ${{matrix.os}}
    permissions:
      packages: write
    steps: *buildcache-steps

  buildcache-macos-arm:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-14, macos-15 ]
        target: [ m1 ]
    runs-on: ${{matrix.os}}
    permissions:
      packages: write
    steps: *buildcache-steps
